-- MAGNITUDE ANALYSIS

-- Total customers by country
select 
country, count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Total customers by gender
select 
gender, count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Total products by category
select
category, count(product_key) total_products
from gold.dim_products
group by category
order by total_products desc

-- Avg cost in each category
select
category, avg(cost) avg_cost
from gold.dim_products
group by category
order by avg_cost desc

-- Total revenue generated for each category
select 
sum(s.sales_amount) total_revenue, p.category
from gold.fact_sales s
left join gold.dim_products p
on p.product_key=s.product_key
group by p.category
order by total_revenue desc

-- Total revenue generated by each customer
select
c.customer_key, c.first_name, c.last_name, 
sum(s.sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_customers as c
on c.customer_key=s.customer_key
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- Distribution of sold items from countries 
select
c.country,
sum(s.quantity) total_sold_items
from gold.fact_sales s
left join gold.dim_customers as c
on c.customer_key=s.customer_key
group by c.country
order by total_sold_items desc